# Generated by Django 2.2.10 on 2020-05-25 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название формата произведения')),
            ],
            options={
                'verbose_name': 'Формат произведения',
                'verbose_name_plural': 'Форматы произведений',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название жанра произведения')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('age_limit', models.CharField(choices=[('0', '0'), ('6', '6'), ('12', '12'), ('16', '16'), ('18', '18')], default='18', max_length=2, verbose_name='Возрастной рейтинг')),
                ('format_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_set', to='translation_app.FormatType', verbose_name='Формат книги')),
                ('genre', models.ManyToManyField(blank=True, related_name='origin_set', to='translation_app.Genre', verbose_name='Жанры')),
                ('origin_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_set', to='translation_app.Language', verbose_name='Язык оригинала')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_app.OriginIcon', verbose_name='Постер произведения')),
                ('source_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_app.OriginFile', verbose_name='Ссылка на произведение')),
            ],
            options={
                'verbose_name': 'Оригинал',
                'verbose_name_plural': 'Оригиналы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала перевода')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_set', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_set', to='translation_app.Language', verbose_name='Язык')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_set', to='translation_app.Origin', verbose_name='Оригинал')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_set', to='translation_app.Translation', verbose_name='Основной перевод')),
                ('version_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_app.VersionFile', verbose_name='Ссылка на версию')),
            ],
            options={
                'verbose_name': 'Версия перевода',
                'verbose_name_plural': 'Версии переводов',
                'ordering': ['translation', '-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='RateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(default=0, verbose_name='Оценка')),
                ('rate_date', models.DateField(auto_now_add=True, verbose_name='Дата оценивания')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_set', to='translation_app.Translation', verbose_name='Перевод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['translation'],
            },
        ),
        migrations.CreateModel(
            name='CommentOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=1000, verbose_name='Текст комментария')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentorigin_set', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_origin_set', to='translation_app.Origin', verbose_name='Книга')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentorigin_child_set', to='translation_app.CommentOrigin', verbose_name='Родительский коментарий')),
            ],
            options={
                'verbose_name': 'Комментарий произведения',
                'verbose_name_plural': 'Комментарии произведений',
                'ordering': ['-post_date', 'origin'],
            },
        ),
    ]
